### ISSUE TITLE
HTTP 405 Method Not Allowed on login

### ISSUE THREAD

**Issue by danir-de** [Code-House/keycloak-discourse#1]
Login fails via Keycloak, when pressing the Login button in discourse. 
It redirects you to Keycloak which itself just throws a generic error message.

```
2024-11-07 02:34:23,975 DEBUG [jdk.event.security] (vert.x-eventloop-thread-0)  TLSHandshake: :65535, TLSv1.3, TLS_AES_256_GCM_SHA384, 0
2024-11-07 02:34:23,979 DEBUG [io.netty.handler.ssl.SslHandler] (vert.x-eventloop-thread-0) [id: 0x180b7421, L:/172.17.0.2:8443 - R:/172.17.0.1:42950] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
2024-11-07 02:34:23,990 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser] (vert.x-eventloop-thread-0) Recalculated absoluteURI to https://chron.id/realms/CHRONICALSde/broker/discourse/endpoint?sso=bm9uY2U9MmQ0MWYxZDk3MWM3YjIxOGYxMWMxZjg1NzczY2Y2YmYmcmV0dXJuX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZjb21tdW5pdHkuY2hyb25pY2Fscy5kZSUyRnNlc3Npb24lMkZzc29fbG9naW4%3D&sig=0bb6779d2a3828b3c5cb7ed2685640045176893838896dc87b0cacea77ccd7e9
2024-11-07 02:34:23,994 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-2) new JtaTransactionWrapper. Was existing transaction suspended: false Request Context: HTTP GET /realms/CHRONICALSde/broker/discourse/endpoint
2024-11-07 02:34:23,996 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-2) `hibernate.connection.provider_disables_autocommit` was enabled.  This setting should only be enabled when you are certain that the Connections given to Hibernate by the ConnectionProvider have auto-commit disabled.  Enabling this setting when the Connections do not have auto-commit disabled will lead to Hibernate executing SQL operations outside of any JDBC/SQL transaction.
2024-11-07 02:34:23,998 DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (executor-thread-2) Hibernate RegisteredSynchronization successfully registered with JTA platform
2024-11-07 02:34:24,000 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Error response Method Not Allowed: jakarta.ws.rs.WebApplicationException: HTTP 405 Method Not Allowed
        at org.jboss.resteasy.reactive.server.handlers.ResourceLocatorHandler.handle(ResourceLocatorHandler.java:71)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-11-07 02:34:24,010 FINE  [freemarker.cache] (executor-thread-2) TemplateLoader.findTemplateSource("template_en_US.ftl"): Not found
2024-11-07 02:34:24,017 FINE  [freemarker.cache] (executor-thread-2) TemplateLoader.findTemplateSource("template_en.ftl"): Not found
2024-11-07 02:34:24,018 FINE  [freemarker.cache] (executor-thread-2) TemplateLoader.findTemplateSource("template.ftl"): Found
2024-11-07 02:34:24,019 FINE  [freemarker.cache] (executor-thread-2) "template.ftl"("en_US", UTF-8, parsed): using cached since jar:file:/opt/keycloak/lib/lib/main/org.keycloak.keycloak-themes-26.0.5.jar!/theme/base/login/template.ftl hasn't changed.
2024-11-07 02:34:24,020 FINE  [freemarker.cache] (executor-thread-2) TemplateLoader.findTemplateSource("footer_en_US.ftl"): Not found
2024-11-07 02:34:24,020 FINE  [freemarker.cache] (executor-thread-2) TemplateLoader.findTemplateSource("footer_en.ftl"): Not found
2024-11-07 02:34:24,021 FINE  [freemarker.cache] (executor-thread-2) TemplateLoader.findTemplateSource("footer.ftl"): Found
2024-11-07 02:34:24,022 FINE  [freemarker.cache] (executor-thread-2) "footer.ftl"("en_US", UTF-8, parsed): using cached since jar:file:/opt/keycloak/lib/lib/main/org.keycloak.keycloak-themes-26.0.5.jar!/theme/base/login/footer.ftl hasn't changed.
2024-11-07 02:34:24,028 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-2) JtaTransactionWrapper rollback. Request Context: HTTP GET /realms/CHRONICALSde/broker/discourse/endpoint
2024-11-07 02:34:24,030 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-2) Initiating JDBC connection release from afterTransaction
2024-11-07 02:34:24,031 DEBUG [org.hibernate.engine.transaction.internal.TransactionImpl] (executor-thread-2) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
2024-11-07 02:34:24,032 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-2) JtaTransactionWrapper end. Request Context: HTTP GET /realms/CHRONICALSde/broker/discourse/endpoint
```

**Comment by splatch** [comment]
Hello Danir,
Just to confirm you login into Keycloak via Discourse and you get error after redirect back to keycloak, once you confirm user credentials on Discourse login form?

Cheers,
Łukasz
